drop all objects;

create table t_product(
  businessNo varchar(10) primary key,
  name varchar(20),
  type varchar (60),
  sum number ,
  unit varchar (30)
);

create table t_user(
  businessNo varchar (10) primary key ,
  name varchar (20),
  address varchar (100),
  birthday varchar (10),
  sex char(3)
);

create table t_sale(
  id bigint generated by default as identity,
  userBusinessNo varchar (10),
  productBusinessNo varchar (10),
  saleDate varchar (10),
  sum number ,
  count number,
  primary key (id)
);

create table t_address(
  id bigint generated by default as identity,
  name varchar (30)
);

//alter table t_sale add constraint fk_sale1 foreign key (userBusinessNo) references t_user(businessNo);
//alter table t_sale add constraint fk_sale2 foreign key (productBusinessNo) references t_product(businessNo);
